### ISSUE TITLE
How I can install and test this plugin?

### ISSUE THREAD

**Issue by cogscides** [Xallt/sync-graph-settings#1]
How I can install and test this plugin? There is no way to install it, am I right?

**Comment by Xallt** [comment]
There's no good way to install the plugin currently because it's not finished yet &mdash; I'll try my best to make it available as soon as possible

**Comment by Xallt** [comment]
@cogscides 
> How I can install and test this plugin? There is no way to install it, am I right?

Good news: the plugin is now part of the Obsidian Community Plugins!
https://obsidian.md/plugins?search=sync%20graph

You can now install the plugin through Obsidian as any other plugin
