### ISSUE TITLE
Not working on my phone 

### ISSUE THREAD

**Issue by funamorisenji** [Xallt/sync-graph-settings#3]
On my mobile device, It said `This plugin doesn't support your device`. How can I fix this issue?

**Comment by ichmoimeyo** [comment]
I don't think there is anything you can do, as the manisfest.json states ... 
"isDesktopOnly": true
... apart from making a feature request to the developer to see whether it is technically possible.

**Comment by Xallt** [comment]
@funamorisenji I only set as available on desktop because I didn't want to test it on a phone
Give me a ~week, I'll try to verify that it works on my Android and if so, will roll out an updated version that should work

**Comment by funamorisenji** [comment]
@Xallt thank Thank you so much! Your plugin is amazing, and I'm really excited to use it on all my devices. Keep up the great work! God bless you man~

**Comment by Xallt** [comment]
@funamorisenji the plugin should now work on mobile!
It should either update by itself on app reload, or you can remove the plugin and install again (it should show that the version is `1.0.2`)
