### ISSUE TITLE
Feature Request: save local graph specific settings

### ISSUE THREAD

**Issue by ras0q** [Xallt/sync-graph-settings#4]
A local graph has some filter settings which a global graph does not have.
- max depth
- include incoming/outgoing/neighbor links

I'd like to save these settings in the plugin settings

**Comment by Xallt** [comment]
Riiight ok I'll try to whip something up, but don't expect it to be soon ;)

**Comment by Xallt** [comment]
Added in https://github.com/Xallt/sync-graph-settings/releases/tag/1.2.0
:wink: 
The updated version should already be up on the Community Plugins, please tell me if something is buggy or doesn't work

**Comment by ras0q** [comment]
@Xallt Thank you!
I was very impressed that you have implemented this so quickly.
I have updated this plugin and it seems to be working fine :+1:
