### ISSUE TITLE
[Feature Request] Sync Link Thickness

### ISSUE THREAD

**Issue by Nydid** [Xallt/sync-graph-settings#7]
Hello!

Could this plugin also sync link thickness in addition to the colors?

![image](https://github.com/user-attachments/assets/d59a23e9-4d5a-46fc-be11-751913ca382b)

**Comment by Xallt** [comment]
Alright, will add this some time later, I'll tag you when it's done

**Comment by Xallt** [comment]
Done @Nydid https://github.com/Xallt/sync-graph-settings/releases/tag/1.4.0
